export enum Enderecamento {
  ESTOQUE_NOVO = 1,
  ESTOQUE_USADO = 2,
  ESTOQUE_TESTE = 3,
  EXCECAO = 4,
  CLIENTE_LOCACAO = 5,
  RECOLHA_TROCA = 6,
  RECOLHA_INATIVIDADE = 7,
  MANUTENCAO = 8,
  TODOS = -1,
}
